swagger: "2.0"
info:
  description: "Locator back service"
  version: "1.0.0"
  title: "Locator"
  termsOfService: ""
  contact:
    email: "zeen@zeen.ru"
host: "locator.com"
basePath: "/"
schemes:
- "https"
paths:
  /file/sendFile:
    post:
      tags:
      - "file"
      summary: "Сохранение файла в файловое хранилище, преобразование имени файла в техническое и сохранение записи в бд, возврат в качестве ответа guid файла"
      description: ""
      operationId: "sendFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/File"
        "400":
          description: "Invalid file supplied"
  /file/getFile/{guid}:
    get:
      tags:
      - "file"
      summary: "Получение файла по его guid"
      description: ""
      operationId: "getFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "guid"
        in: "path"
        description: ""
        required: true
        type: "string"
        format: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/File"
        "400":
          description: "Invalid file supplied"
definitions:
  File:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      filename:
        type: "string"
        format: "string"
      realfilename:
        type: "string"
        format: "string"
      serverCdnId:
        $ref: "#/definitions/ServerCdn"
      deleted:
        type: "boolean"
        default: false
  ServerCdn :
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        format: "string"
      url:
        type: "string"
        format: "string"
      deleted:
        type: "boolean"
        default: false
